apiVersion: v1
kind: List
items:
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: ppe-web-${webapp-name}
  spec:
    replicas: 3
    template:
      metadata:
        labels:
          run: ppe-web-${webapp-name}
      spec:
        containers:
          - name: ppe-web-${webapp-name}
            image: 798283861836.dkr.ecr.eu-west-1.amazonaws.com/ppe-web-${webapp-name}:master
            imagePullPolicy: Always
            ports:
              - containerPort: 4000
            env:
              - name: PUBLIC_DIR
                value: "public"
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                configMapKeyRef:
                  name: newrelic-config
                  key: newrelic_key
            - name: NEW_RELIC_ENABLED
              value: "true"
            readinessProbe:
              httpGet:
                path: /health
                port: 4000
              initialDelaySeconds: 5
              periodSeconds: 2
            livenessProbe:
              httpGet:
                path: /health
                port: 4000
              initialDelaySeconds: 7
              periodSeconds: 2

- apiVersion: v1
  kind: Service
  metadata:
    name: ppe-web-${webapp-name}
    labels:
      run: ppe-web-${webapp-name}
  spec:
    ports:
    - port: 4000
    selector:
      run: ppe-web-${webapp-name}
