apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        run: {{ .Chart.Name }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: run
                    operator: In
                    values:
                      - {{ .Chart.Name }}
              topologyKey: "kubernetes.io/hostname"
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: run
                      operator: In
                      values:
                        - {{ .Chart.Name }}
                topologyKey: "failure-domain.beta.kubernetes.io/zone"
      containers:
        - name: {{ .Chart.Name }}
{{if .Values.image.sha}}
          image: "{{ .Values.image.repository }}@{{ .Values.image.sha }}"
{{else}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
{{end}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port}}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.managementPort }}
            initialDelaySeconds: 5
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.managementPort }}
            initialDelaySeconds: 7
            periodSeconds: 2
          env:
          - name: PUBLIC_DIR
            value: "public"
          - name: NEW_RELIC_ENABLED
            value: "{{ .Values.newrelic.enabled }}"
{{if .Values.newrelic.enabled}}
          - name: NEW_RELIC_APP_NAME
            value: "{{ .Chart.Name }}"
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              configMapKeyRef:
                name: newrelic-config
                key: newrelic_key
{{end}}
